all:
  children:
    es_nodes:
      hosts:
        es-node1:
          ansible_host: <IP>
        es-node2:
          ansible_host: <IP>
        es-node3:
          ansible_host: <IP>
    kibana:
      hosts:
        kibana-node:
          ansible_host: <IP>

    elasticsearch:
      children:
        es_nodes:

